const EMPLOYEE_PREFIX = "UI";
const EMPLOYEE_UID_LENGTH = 7;
const ALPHA_NUMERIC =
  "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
const VALID_STARTING_PHONE_NUMBERS = ["8", "9"];
const PHONE_NUMBER_LENGTH = 8;

module.exports = {
  EMPLOYEE_PREFIX,
  EMPLOYEE_UID_LENGTH,
  ALPHA_NUMERIC,
  VALID_STARTING_PHONE_NUMBERS,
  PHONE_NUMBER_LENGTH
};
